name: 식단 알림 발송

on:
  schedule:
    - cron: '30 21 * * *'
    - cron: '0 2 * * *'
    - cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  send-sikdan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: 라이브러리 설치
        run: pip install requests
      - name: 식단 발송
        run: python sikdan.py
